version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 10s
      retries: 5
  mq:
    image: mq
    depends_on: 
      - rabbitmq
    container_name: mq
    restart: 'no'
    environment: 
      NODE_ENV: ${NODE_ENV:-production}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://rabbitmq:5672}
networks: 
  default:
    name: test-env
