on: [push]

name: Lint & Build

jobs:
  build:
    name: mq-nodejs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      id: npm-install
      run: npm install

    - name: Lint
      id: lint-project
      run: npm run lint

    - name: Build
      id: build-project
      run: npm run build
    