on: [push]

name: Build Docker Image

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      id: build-image
      run: docker build -t mq