on: [push]

name: Lint

jobs:
  deploy:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      id: lint-project
      run: npm run lint